// client-React/src/containers/chartForm/chartForm.js
import React, { Component } from 'react'

import Form from '../../components/Form/Form'
import Input from '../../components/Form/inputs/input'

class ChartForm extends Component {
    state = {
        calendario: "2022-07-10",
        dineroInicial: 0,
        porcentaje: 5.369,
        ingresoExtraMensual: 2854.18,
        cantidadConsultar: 50
    }

    handleInputChange = async (event) => {
        const target = event.target
        const id = target.id
        await this.setState({
            [id]: target.value
        })
        this.props.submit(this.state)
    }

    render() {
        return (
            <Form submit={() => this.props.submit(this.state)} title="Interes Compuesto">
                <div className="col-sm-12 col-md-3">
                    <Input type="date" id="calendario" value={this.state.calendario} onChange={this.handleInputChange}>Fecha limite: </Input>
                    <Input type="number" min="0" step="0.001" id="dineroInicial" value={this.state.dineroInicial} onChange={this.handleInputChange}>Dinero Inicial: </Input>
                </div>
                <div className="col-sm-12 col-md-3">
                    <Input type="number" min="0" step="0.001" id="porcentaje" value={this.state.porcentaje} onChange={this.handleInputChange}>Porcentaje: </Input>
                    <Input type="number" min="0" step="0.001" id="ingresoExtraMensual" value={this.state.ingresoExtraMensual} onChange={this.handleInputChange}>Ingreso extra mensual: </Input>
                </div>
                <div className="col-sm-12 col-md-3">
                    <Input type="number" min="0" step="0.001" id="cantidadConsultar" value={this.state.cantidadConsultar} onChange={this.handleInputChange}>Cantidad a consultar: </Input>
                    <button type="submit" className="col-sm-3 col-md-5 btn btn-primary float-left mt-4">Aceptar</button>
                </div>
            </Form>
        )
    }
}

export default ChartForm

// client-Angular/src/app/chart-form/chart-form.component.ts
import { Component, OnInit } from '@angular/core';

import { NgForm } from '@angular/forms'
import { InteresCompuestoService } from '../services/interes-compuesto.service'
import { InteresCompuestoRes } from '../models/interes-compuesto-res'

import Chart from 'chart.js'

@Component({
  selector: 'app-chart-form',
  templateUrl: './chart-form.component.html',
  styleUrls: ['./chart-form.component.css']
})
export class ChartFormComponent implements OnInit {

  myChart = Chart

  constructor(public interesCompuestoService: InteresCompuestoService) { }

  ngOnInit(): void {

    const canvas = <HTMLCanvasElement>document.getElementById('myChart')
    const ctx = canvas.getContext('2d');
    this.myChart = new Chart(ctx, {
      type: "line",
      data: {
        //Bring in data
        labels: this.interesCompuestoService.interesCompuestoRes.meses,
        datasets: [
          {
            label: "Interes Compuesto",
            data: this.interesCompuestoService.interesCompuestoRes.interesesCompuestos,
            borderColor: 'green',
            backgroundColor: 'rgba(255,255,255,0)',
            borderWidth: 2,
          },
          {
            label: "Ingreso Extra Mensual",
            data: this.interesCompuestoService.interesCompuestoRes.ingresosExtrasMensuales,
            borderColor: 'blue',
            backgroundColor: 'rgba(255,255,255,0)',
            borderWidth: 2
          },
          {
            label: "Dinero inicial",
            data: this.interesCompuestoService.interesCompuestoRes.dinerosIniciales,
            borderColor: 'black',
            backgroundColor: 'rgba(255,255,255,0)',
            borderWidth: 2
          }
        ]
      },
      options: {
          /* scales: {
              yAxes: [{
                  ticks: {
                      beginAtZero: true
                  }
              }]
          }, */ tooltips: {
          mode: 'x'
        }
      }
    });
  }

  submit(form: NgForm) {
    this.interesCompuestoService.postInteresCompuesto(form.value).subscribe(res => {
      this.interesCompuestoService.interesCompuestoRes = res as InteresCompuestoRes
      this.myChart.data.labels = this.interesCompuestoService.interesCompuestoRes.meses
      this.myChart.data.datasets[0].data = this.interesCompuestoService.interesCompuestoRes.interesesCompuestos
      this.myChart.data.datasets[1].data = this.interesCompuestoService.interesCompuestoRes.ingresosExtrasMensuales
      this.myChart.data.datasets[2].data = this.interesCompuestoService.interesCompuestoRes.dinerosIniciales
      this.myChart.update()
    })
  }

}

<!-- <onSubmit={this.handleSubmit}> -->
<form #interesCompuestoForm="ngForm" (ngSubmit)="submit(interesCompuestoForm)">
    <div class="row">
        <div class="col text-center">
            <h1>Interes Compuesto</h1>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-3">
            <!-- <Input type="date" id="calendario" value={this.state.calendario} onChange={this.handleInputChange}>Fecha
            limite:
            </Input> -->
            <div class="form-group">
                <label>Fecha limite: </label>
                <input type=date class="form-control" name="calendario"
                    [(ngModel)]="interesCompuestoService.interesCompuesto.calendario" />
            </div>
            <!-- <Input type="number" min="0" step="0.001" id="dineroInicial" value={this.state.dineroInicial}
                onChange={this.handleInputChange}>Dinero Inicial: </Input> -->
            <div class="form-group">
                <label>Dinero Inicial: </label>
                <input type=number class="form-control" min="0" step="0.001" name="dineroInicial"
                    #dineroIncial="ngModel" [(ngModel)]="interesCompuestoService.interesCompuesto.dineroInicial" />
            </div>
        </div>
        <div class="col-sm-12 col-md-3">
            <!-- <Input type="number" min="0" step="0.001" id="porcentaje" value={this.state.porcentaje}
                onChange={this.handleInputChange}>Porcentaje: </Input>
            <Input type="number" min="0" step="0.001" id="ingresoExtraMensual" value={this.state.ingresoExtraMensual}
                onChange={this.handleInputChange}>Ingreso extra mensual: </Input> -->
            <div class="form-group">
                <label>Porcentaje: </label>
                <input type=number class="form-control" min="0" step="0.001" name="porcentaje"
                    [(ngModel)]="interesCompuestoService.interesCompuesto.porcentaje" />
            </div>
            <div class="form-group">
                <label>Ingreso Extra Mensual: </label>
                <input type=number class="form-control" min="0" step="0.001" name="ingresoExtraMensual"
                    [(ngModel)]="interesCompuestoService.interesCompuesto.ingresoExtraMensual" />
            </div>
        </div>
        <div class="col-sm-12 col-md-3">
            <!-- <Input type="number" min="0" step="0.001" id="cantidadConsultar" value={this.state.cantidadConsultar}
                onChange={this.handleInputChange}>Cantidad a consultar: </Input> -->
            <div class="form-group">
                <label>Cantidad a Consultar: </label>
                <input type=number class="form-control" min="0" step="0.001" name="cantidadConsultar"
                    [(ngModel)]="interesCompuestoService.interesCompuesto.cantidadConsultar" />
            </div>
            <button type="submit" class="col-sm-3 col-md-5 btn btn-primary float-left mt-4">Aceptar</button>
        </div>
    </div>
</form>
